version: '3.9'
services:
  api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      PORT: 3001
      JWT_SECRET: 099148eb414bd717a855e8514d74c0dbec5ab4dbd33ce5b23fd62236af7e74a6
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: articles
      DB_PASSWORD: adm_123
      DB_NAME: articles_db
      DATABASE_URL: postgres://articles:adm_123@db:5432/articles_db
    ports:
      - '3001:3001'
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:13
    container_name: articles_gd_db
    environment:
      POSTGRES_USER: articles
      POSTGRES_PASSWORD: adm_123
      POSTGRES_DB: articles_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
volumes:
  db_data:
